databases:
  - name: app_scraping_twiter
    databaseName: app_scraping_twiter
    user: app_scraping_twiter

services:
  - type: web
    name: app_scraping_twiter
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_scraping_twiter
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false